[package]
name = "tester"
version = "0.1.0"
edition = "2021"

[dependencies]
asciicast = "0.2.2"
rand = "0.8.5"
serde_json = "1.0.125"
serialport = "4.5.0"
ssh2 = "0.9.4"
subprocess = "0.2.9"
tokio = { version = "1", features = ["full"] }
